---
exclude: ^$
default_stages: [commit]
default_language_version: {python: python3.8}
files: ''
fail_fast: false
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        name: ruff
        description: Run 'ruff' for extremely fast Python linting
        types_or: [python, pyi]
        args: [--fix]
      - id: ruff-format
        name: ruff-format
        description: Run 'ruff format' for extremely fast Python formatting
        types_or: [python, pyi]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        name: mypy
        description: Run mypy static analysis tool
        types_or: [python, pyi]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-xml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files
        args: [maxkb=51200]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-symlinks
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: local
    hooks:
      - id: changelogs-rst
        name: changelogs must be rst
        entry: changelog filenames must end in .rst
        language: fail
        files: changelog/.*(?<!\.rst)$
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.17.0
    hooks:
      - id: yamlfix
        name: yamlfix
        entry: yamlfix
        language: python
        language_version: python3
        types: [yaml]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: prettier
        description: ''
        types_or: [json, javascript, css]
        args: []
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
        name: Shell Syntax Check
        description: Check Shell Syntax on ALL staged files with user friendly messages
          and colors
        entry: pre_commit_hooks/shell-lint.sh
        language: script
        types: [shell]
        args: [--format=json]
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: shellcheck
        name: Test shell scripts with shellcheck
        description: Shell scripts conform to shellcheck
        types: [shell]
        entry: hooks/shellcheck.sh
        language: script
        exclude_types: [csh, perl, python, ruby, tcsh, zsh]
        args: [-e, SC1091]
      - id: shfmt
        name: Check shell style with shfmt
        language: script
        entry: hooks/shfmt.sh
        types: [shell]
        exclude_types: [csh, perl, python, ruby, tcsh, zsh]
        args: [-l, -i, '2', -ci, -w, -d]
  - repo: https://github.com/mrtazz/checkmake
    rev: 0.2.2
    hooks:
      - id: checkmake
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: htmlhint
        args: [--config, .htmlhintrc]
      - id: dockerfile_lint
        args: [--json, --verbose, --dockerfile]
  # - repo:
  #   rev:
  #   hooks:
  #     - id:
