---
exclude: ^$
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        name: ruff
        description: Run 'ruff' for extremely fast Python linting
        types_or: [python, pyi]
        args: [--fix]
        additional_dependencies: [toml]
      - id: ruff-format
        name: ruff-format
        description: Run 'ruff format' for extremely fast Python formatting
        types_or: [python, pyi]
        additional_dependencies: [toml]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        name: mypy
        description: Run mypy static analysis tool
        types_or: [python, pyi]
        additional_dependencies: [toml]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
  - repo: local
    hooks:
      - id: changelogs-rst
        name: changelogs must be rst
        entry: changelog filenames must end in .rst
        language: fail
        files: changelog/.*(?<!\.rst)$
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.17.0
    hooks:
      - id: yamlfix
        name: yamlfix
        entry: yamlfix
        language: python
        language_version: python3
        types: [yaml]
        additional_dependencies: [toml]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: prettier
        description: ''
        types_or: [json, javascript, css]
        args: []
