[tool.poetry]
name = "reptile"
version = "0.1.0"
description = ""
authors = ["nianwei100"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
ipykernel = "^6.29.5"
python-dotenv = "^1.0.1"
requests = "^2.32.3"
loguru = "^0.7.2"
aiohttp = "^3.10.5"
fake-useragent = "^1.5.1"
ruff = "^0.6.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


