[tool.poetry]
name = "reptile"
version = "0.1.0"
description = ""
authors = ["nianwei"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[tool.poetry.group.dev.dependencies]
yapf = "^0.40.2"
pylint = "^3.2.7"
rich = "^13.8.1"
ipykernel = "^6.29.5"
mypy = "^1.11.2"
pretty-errors = "^1.2.25"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
