[tool.poetry]
name = "reptile"
version = "0.1.0"
description = ""
authors = ["nianwei100"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
ipykernel = "^6.29.5"
python-dotenv = "^1.0.1"
requests = "^2.32.3"
loguru = "^0.7.2"
aiohttp = "^3.10.5"
fake-useragent = "^1.5.1"
xmltodict = "^0.13.0"
colorama = "^0.4.6"
jieba = "^0.42.1"
bs4 = "^0.0.2"
opencv-python = "^4.10.0.84"
yapf = "^0.40.2"
mypy = "^1.11.2"
pylint = "^3.2.7"
arrow = "^1.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


